version: '3.8'

services:
  postgres_service:
    image: postgres:13
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network
  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-api
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgres_service
    networks:
      - nest_network
    volumes:
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_CONFIG: '{"Servers": {"1": {"Name": "PostgreSQL", "Group": "Servers", "Host": "postgres_service", "Port": 5432, "Username": "myuser", "Password": "mypassword", "SSLMode": "prefer"}}}'
    ports:
      - "5050:80"
    depends_on:
      - postgres_service
    networks:
      - nest_network
volumes:
  postgres_data:

networks:
  nest_network:
